version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
  cypress:
    image: "cypress/included:9.4.1"
    environment:
      - CYPRESS_baseUrl=http://web:3000
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/quitcost
      - bundle:/quitcost/vendor/bundle
      - node_modules:/quitcost/node_modules
      - tmp:/quitcost/tmp
    ports:
      - "3000:3000"
      - "3035:3035"
      # Ports required for debugging
      - "1234:1234"
      - "26168:26168"
    environment:
      BINDING: "0.0.0.0"
    depends_on:
      - db
      - chrome
volumes:
  node_modules:
  bundle:
  tmp:
