version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/quitcost
    ports:
      - "3000:3000"
      # Ports required for debugging
      - "1234:1234"
      - "26168:26168"
    environment:
      BINDING: "0.0.0.0"
    depends_on:
      - db
