version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
  web:
    build: .
    command: tail -f /dev/null
    volumes:
      - .:/quitcost
      - node_modules:/quitcost/node_modules
    ports:
      - "3000:3000"
      - "3035:3035"
      # Ports required for debugging
      - "1234:1234"
      - "26162:26162"
    environment:
      BINDING: "0.0.0.0"
    depends_on:
      - db
volumes:
  node_modules:
