name: タスク
description: タスクを追加する場合はこちらから
assignees: IkumaTadokoro
body:
  - type: markdown
    attributes:
      value: "タスクの登録。以下のフォームを入力してください。"
  - type: textarea
    id: subtask
    attributes:
      label: サブタスク
      value: |
        - [ ]
    validations:
      required: false
  - type: textarea
    id: note
    attributes:
      label: メモ
    validations:
      required: false
