name: Move new issues into Kanban
on:
  issues:
    types: [opened]

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Kanban
          column: インボックス
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
